projectRoot = "../.."

compilerFrontend="gcc"
compiler = "clang++"
ar = "ar"

flags = [
    "-std=c++20",
    "-O3",
    "-g",
    "-fsanitize=address",
    "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
    "-fsanitize=undefined",
    "-Wall",
]

[[builds]]                              
    name = "libraryname"
    buildRule = "staticLibrary" # or dynamicLibrary
    outputName = "LibraryName"
    sourceFiles = ["lib/*.cpp"]
    includePaths = ["include"]

[[builds]]
    name = "tests"
    buildRule = "executable"
    requires = ["libraryname"]
    outputName = "Tests"
    sourceFiles = ["tests/*.cpp"]
    includePaths = ["include"]
    # The libraryPaths and libraries fields can be used to specify additional
    # libraries and paths to the build. This allows for linking against third 
    # party libraries.
    #libraryPaths = [] 
    #libraries = [] 

[[builds]]
    name = "application"
    buildRule = "executable"
    requires = ["libraryname"]
    outputName = "Applicatoin"
    sourceFiles = ["src/*.cpp"]
    includePaths = ["include"]
