projectRoot = "../.."

compiler = "clang++"
ar = "ar"
compilerFrontend="gcc"

flags = [
    "-std=c++11",
    "-g"
]

[[builds]]                              
    name = "calculatorstatic"
    buildRule = "staticlib"
    outputName = "Calculator"
    srcDirs = ["src"]
    includePaths = ["include"]

[[builds]]
    name = "calculatordynamic"
    buildRule = "dynamiclib"
    outputName = "Calculator"
    srcDirs = ["src"]
    includePaths = ["include"]

[[builds]]
    name = "tests"
    buildRule = "exe"
    requires = ["calculatorstatic"]
    outputName = "CalculatorTests"
    srcDirs = ["tests"]
    includePaths = ["include"]
    #libraryPaths = []                   # additional library paths, used for including third party libraries.
    #libraries = []                      # additional libraries, used for including third party libraries.

[[builds]]
    name = "calculatorapp"
    buildRule = "exe"
    requires = ["calculatordynamic"]
    outputName = "CalculatorApp"
    srcDirs = ["src"]
    includePaths = ["include"]
    #libraryPaths = []                   # additional library paths, used for including third party libraries.
    #libraries = []                      # additional libraries, used for including third party libraries.
