projectRoot = "../.."

compiler = "clang++"
ar = "ar"
compilerFrontend="gcc"

flags = [
    "-std=c++17",
    "-O3",
    "-g",
    "-fsanitize=address",
    "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
    "-fsanitize=undefined",
    "-Wall",
]

[[builds]]                              
    name = "calculatorstatic"
    buildRule = "staticlib"
    outputName = "CalculatorStatic"
    srcDirs = ["lib"]
    includePaths = ["include"]

[[builds]]
    name = "calculatordynamic"
    buildRule = "dynamiclib"
    outputName = "CalculatorShared"
    srcDirs = ["lib"]
    includePaths = ["include"]

[[builds]]
    name = "calculatortests"
    buildRule = "exe"
    requires = ["calculatorstatic"]
    outputName = "CalculatorTests"
    srcDirs = ["tests"]
    includePaths = ["include"]
    # The libraryPaths and libraries fields can be used to specify additional
    # libraries and paths to the build. This allows for linking against third
    # party libraries.
    #libraryPaths = []
    #libraries = []

[[builds]]
    name = "calculatorapp"
    buildRule = "exe"
    requires = ["calculatordynamic"]
    outputName = "CalculatorApp"
    srcDirs = ["src"]
    includePaths = ["include"]
