projectRoot = "../../"
compiler = "clang-cl"
archiver = "llvm-ar"
compilerFrontend="msvc"

flags = [
    "/std:c++17",
    "/Zi",
]

[[builds]]
name = "calculatorstatic"
buildRule = "staticLib"
outputName = "CalculatorStatic"
sourceFiles = ["lib/*.cpp"]
includePaths = ["include"]

[[builds]]
name = "calculatordynamic"
buildRule = "dynamicLib"
outputName = "CalculatorShared"
sourceFiles = ["lib/*.cpp"]
includePaths = ["include"]

[[builds]]
name = "calculatortests"
buildRule = "exe"
requires = ["calculatordynamic"]
outputName = "CalculatorTests"
sourceFiles = ["tests/*.cpp"]
includePaths = ["include"]
# The libraryPaths and libraries fields can be used to specify additional
# libraries and paths to the build. This allows for linking against third
# party libraries.
#libraryPaths = []
#libraries = []

[[builds]]
name = "calculatorapp"
buildRule = "exe"
requires = ["calculatordynamic"]
outputName = "CalculatorApp"
sourceFiles = ["src/*.cpp"]
includePaths = ["include"]
